# pre-commit configuration set up to use poetry to keep a unified environment
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint nerves_hub_client
        language: system
        always_run: true
        pass_filenames: false
      - id: black
        name: black
        entry: poetry run black nerves_hub_client tests
        language: system
        always_run: true
        pass_filenames: false
